require('sinatra')
require('sinatra/contrib/all')
require('pry-byebug')
require_relative('models/rps_game.rb')




# contains all the 'get' statements

# get() is an http method
# get() method takes a string as a parameter, and a block.
# get('webpage')  i.e. route = method(path)
# do
# action this code when a get request is sent to that particular location
# whatever the final action in the block is, becomes the body of the html generated by the request.
# If you want it to be displayed directly, it has to return a string.
# the fact that we include p 'string' means nothing to Sinatra
# end

get("/play/:weapon") do
  weapon = params[:weapon].to_s
  game = Game.new(weapon)
  game_result = game.play()
  @result = "You played #{weapon} and I played #{game.computer_choice}.  You #{game_result}!"
  erb(:result)
end

get("/welcome") do
  erb(:welcome)
end#
