require('sinatra')
require('sinatra/contrib/all')
require('pry-byebug')
require_relative('models/rps_game.rb')




# contains all the 'get' statements

# get() is an http method
# get() method takes a string as a parameter, and a block.
# get('webpage')  i.e. route = method(path)
# do
# action this code when a get request is sent to that particular location
# whatever the final action in the block is, becomes the body of the html generated by the request.
# If you want it to be displayed directly, it has to return a string.
# the fact that we include p 'string' means nothing to Sinatra
# end

get("/rock") do
  p "Rock"
  erb(:result)
end

get ("/paper") do
  p "Paper"
  erb(:result)
end

get ("/scissors") do
  p "Scissors"
  erb(:result)
end
